### ISSUE TITLE
Error in task "default ports for poudriere is initialized"

### ISSUE THREAD

**Issue by kadecole** [uchida/ansible-poudriere-role#1]
When I run this role I get the following error:

> TASK: [ansible-poudriere-role | default ports for poudriere is initialized] **\* 
> fatal: [ports.net.siue.edu] => error while evaluating conditional: portsnap != "none"
> 
> FATAL: all hosts have already failed -- aborting

It appears to work correctly if I change the line 45 in tasks/freebsd.yml from
`when: '{{ poudriere_portsmethod }} != "none"'`
to:
`when: '"{{ poudriere_portsmethod }}" != "none"'`

**Comment by uchida** [comment]
Thank you for reporting issue and fixes.
I'm planning to update test environment for this role within 1-2 weeks, so I will fix it with these updates.
However, @kadecole, if you need this fix immediately, I will fix and release 0.3.1.

**Comment by kadecole** [comment]
I fixed it in my clone locally. I will wait for your updates and then test again. Thanks for looking into this.

**Comment by uchida** [comment]
This issue fixed with CI and 0.3.1, fixed version, is available on Ansible Galaxy.
